
POST   http://localhost:8080/student/signup
content-Type: application/json

{
    "fName":"Augustine",
    "lName":"Ngobie",
    "studentId":"SP20-BSE-108",
    "institution":"COMSATS",
    "email":"ngobie@gmail.com",
    "password":"salvation2509"
}

###

POST   http://localhost:8080/student/login
content-Type: application/json

{
    "email":"ngobie@gmail.com",
    "password":"salvation2509"
}


###
POST   http://localhost:8080/student/logout
content-Type: application/json

{
    "email":"ngobie@gmail.com",
    "password":"salvation2509"
}